# Database Schema Viewer
This notebook connects to the SQL Server database using the credentials from the `.env` file and displays the database schema.

In [2]:
import os
import urllib.parse
import sqlalchemy as sa
from dotenv import load_dotenv
from langchain_community.utilities import SQLDatabase

# Load environment variables from .env file
load_dotenv()

True

### Connect to Database
Here we construct the connection string and test the connection.

In [3]:
DB_SERVER = os.getenv("DB_SERVER", "localhost")
DB_PORT   = os.getenv("DB_PORT", "1433")
DB_USER   = os.getenv("DB_USER", "")
DB_PASS   = os.getenv("DB_PASS", "")
DB_NAME   = os.getenv("DB_NAME", "NexonDB")

if DB_USER and DB_PASS:
    connection_string = (
        f"mssql+pyodbc://{DB_USER}:{urllib.parse.quote_plus(DB_PASS)}"
        f"@{DB_SERVER}:{DB_PORT}/{DB_NAME}"
        "?driver=ODBC+Driver+17+for+SQL+Server"
        "&Encrypt=no&TrustServerCertificate=YES"
    )
else:
    connection_string = (
        f"mssql+pyodbc://@{DB_SERVER}/{DB_NAME}"
        "?driver=ODBC+Driver+17+for+SQL+Server"
        "&Trusted_Connection=yes&TrustServerCertificate=YES"
    )

try:
    engine = sa.create_engine(connection_string)
    # Test connection
    with engine.connect() as conn:
        print("Successfully connected to the database!")
except Exception as e:
    print(f"Failed to connect: {e}")

C:\Users\Asus\AppData\Local\Temp\ipykernel_26288\3413723375.py:24: SAWarning: Unrecognized server version info '17.0.4025.3'.  Some SQL Server features may not function properly.
  with engine.connect() as conn:

Successfully connected to the database!

### Display Schema
Using Langchain's SQLDatabase utility to fetch and display the schema.

In [4]:
try:
    db = SQLDatabase.from_uri(connection_string)
    table_info = db.table_info
    
    print("="*50)
    print("DATABASE SCHEMA")
    print("="*50)
    print(table_info)
except Exception as e:
    print(f"Failed to fetch schema: {e}")

d:\anaconda\Lib\site-packages\langchain_community\utilities\sql_database.py:81: SAWarning: Unrecognized server version info '17.0.4025.3'.  Some SQL Server features may not function properly.
  self._inspector = inspect(self._engine)

==================================================
DATABASE SCHEMA
==================================================

CREATE TABLE [AspNetRoleClaims] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[RoleId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimType] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimValue] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE
)

/*
3 rows from AspNetRoleClaims table:
Id	RoleId	ClaimType	ClaimValue

*/


CREATE TABLE [AspNetRoles] (
	[Id] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NormalizedName] NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConcurrencyStamp] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_AspNetRoles] PRIMARY KEY ([Id])
)

/*
3 rows from AspNetRoles table:
Id	Name	NormalizedName	ConcurrencyStamp
6d848ac1-4215-49a3-be6b-2dac91f0f2c7	User	USER	None
e07ca5c7-d8d9-4eda-9fb6-ea4cdc6f2632	Admin	ADMIN	None
*/


CREATE TABLE [AspNetUserClaims] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimType] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimValue] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
)

/*
3 rows from AspNetUserClaims table:
Id	UserId	ClaimType	ClaimValue

*/


CREATE TABLE [AspNetUserLogins] (
	[LoginProvider] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProviderKey] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProviderDisplayName] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY ([LoginProvider], [ProviderKey]),
	CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
)

/*
3 rows from AspNetUserLogins table:
LoginProvider	ProviderKey	ProviderDisplayName	UserId

*/


CREATE TABLE [AspNetUserRoles] (
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RoleId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY ([UserId], [RoleId]),
	CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
)

/*
3 rows from AspNetUserRoles table:
UserId	RoleId
153aed1d-66b0-412e-a4c3-2ef436b5d3c6	6d848ac1-4215-49a3-be6b-2dac91f0f2c7
2321f034-426e-406c-a0de-5a0558b70352	6d848ac1-4215-49a3-be6b-2dac91f0f2c7
23fa1635-1535-4a57-8406-378109d43d98	6d848ac1-4215-49a3-be6b-2dac91f0f2c7
*/


CREATE TABLE [AspNetUserTokens] (
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LoginProvider] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Value] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY ([UserId], [LoginProvider], [Name]),
	CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
)

/*
3 rows from AspNetUserTokens table:
UserId	LoginProvider	Name	Value

*/


CREATE TABLE [AspNetUsers] (
	[Id] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FullName] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[NationalId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IdCardImage] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AccountStatus] INTEGER NOT NULL,
	[Balance] DECIMAL(10, 2) NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[UserName] NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NormalizedUserName] NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Email] NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NormalizedEmail] NVARCHAR(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmailConfirmed] BIT NOT NULL,
	[PasswordHash] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SecurityStamp] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConcurrencyStamp] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhoneNumber] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhoneNumberConfirmed] BIT NOT NULL,
	[TwoFactorEnabled] BIT NOT NULL,
	[LockoutEnd] DATETIMEOFFSET NULL,
	[LockoutEnabled] BIT NOT NULL,
	[AccessFailedCount] INTEGER NOT NULL,
	[City] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Iscertificated] BIT NOT NULL DEFAULT (CONVERT([bit],(0))),
	[LastLogin] DATETIME2 NOT NULL DEFAULT ('0001-01-01T00:00:00.0000000'),
	governorate NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sex NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BlockReason] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BlockedUntil] DATETIME2 NULL,
	[RejectionReason] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ImageUrl] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_AspNetUsers] PRIMARY KEY ([Id])
)

/*
3 rows from AspNetUsers table:
Id	FullName	NationalId	IdCardImage	AccountStatus	Balance	CreatedAt	UserName	NormalizedUserName	Email	NormalizedEmail	EmailConfirmed	PasswordHash	SecurityStamp	ConcurrencyStamp	PhoneNumber	PhoneNumberConfirmed	TwoFactorEnabled	LockoutEnd	LockoutEnabled	AccessFailedCount	City	Country	Iscertificated	LastLogin	governorate	sex	BlockReason	BlockedUntil	RejectionReason	ImageUrl
153aed1d-66b0-412e-a4c3-2ef436b5d3c6	string	12345678963	/uploads/idcards/82a95a3c-019e-46e5-9fe4-f2d7519e5832.png	3	0.00	2026-04-12 23:32:51.983951	string	STRING	string	STRING	False	AQAAAAIAAYagAAAAEAn6cU8jt5os8lNGEP9yVw/h49/e2kJjkIGKt5lW8bhaxr5Q4RSelYX9WrbRCAdERA==	ZP47PH5LRF3273RTB4VRCZTYN7CERWCA	e925d06a-f0a3-4fd2-9ed3-47fec197a048	string	False	False	None	True	0	string	string	True	2026-04-12 23:32:51.983929	string	string	hiiiiiiiiiiiiiiii	None	None	None
2321f034-426e-406c-a0de-5a0558b70352	rawan	123456789124	/uploads/idcards/5cb9c987-1a10-4bea-95a8-df1e9dfdc8c0.png	3	0.00	2026-04-11 18:33:36.721674	rawanselima@gmail.com	RAWANSELIMA@GMAIL.COM	rawanselima@gmail.com	RAWANSELIMA@GMAIL.COM	False	AQAAAAIAAYagAAAAEBds3iljZgZUvS0ijNevKlaIZbqvWSBOcQM3KQZH0yxvy42QTP0WipbmLJMRiqlTrQ==	SFFV3BOM5TR7D3OYN2OWOC3N2NU4MTDW	2c0f38b7-c888-4e90-88a6-42e5e587e9cd	None	False	False	None	True	0	None	None	False	0001-01-01 00:00:00	None	None	giiiiiiiiiiii	None	None	None
23fa1635-1535-4a57-8406-378109d43d98	rawan	123456789123	/uploads/idcards/4b99f5bc-e97c-4a55-b514-92f990c7b8db.png	1	0.00	2026-04-11 17:31:59.773008	rawanselima2@gmail.com	RAWANSELIMA2@GMAIL.COM	rawanselima2@gmail.com	RAWANSELIMA2@GMAIL.COM	False	AQAAAAIAAYagAAAAEL7On9Pey25L/87R+Si76B3YLVekysUkubJwHZvN/2tpXQ2GqDgvvCsq7Bt2ZY1Atg==	JHT2RIFVXNX6ACF2QALDJRDCKG52ZOEK	665548a9-73af-4a0d-9cc3-9be80604bfb7	None	False	False	None	True	0	None	None	True	0001-01-01 00:00:00	None	None	None	None	None	None
*/


CREATE TABLE [Categories] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_Categories] PRIMARY KEY ([Id])
)

/*
3 rows from Categories table:
Id	Name	CreatedAt
1	Electronics	2026-04-07 14:47:35.950000
2	Sports	2026-04-07 14:47:36.046666
3	Cameras	2026-04-07 14:47:36.203333
*/


CREATE TABLE [ChatMessages] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[SenderId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ReceiverId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProductId] INTEGER NULL,
	[Message] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IsRead] BIT NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_ChatMessages] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_ChatMessages_AspNetUsers_ReceiverId] FOREIGN KEY([ReceiverId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_ChatMessages_AspNetUsers_SenderId] FOREIGN KEY([SenderId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_ChatMessages_Products_ProductId] FOREIGN KEY([ProductId]) REFERENCES [Products] ([Id]) ON DELETE SET NULL
)

/*
3 rows from ChatMessages table:
Id	SenderId	ReceiverId	ProductId	Message	IsRead	CreatedAt

*/


CREATE TABLE [Favorites] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProductId] INTEGER NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_Favorites] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Favorites_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_Favorites_Products_ProductId] FOREIGN KEY([ProductId]) REFERENCES [Products] ([Id]) ON DELETE CASCADE
)

/*
3 rows from Favorites table:
Id	UserId	ProductId	CreatedAt

*/


CREATE TABLE [PlatformSettings] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[Key] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Value] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UpdatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_PlatformSettings] PRIMARY KEY ([Id])
)

/*
3 rows from PlatformSettings table:
Id	Key	Value	UpdatedAt
1	CommissionPercentage	10	2026-04-13 20:59:39.183917
*/


CREATE TABLE [ProductImages] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[ProductId] INTEGER NOT NULL,
	[ImageUrl] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IsPrimary] BIT NOT NULL,
	CONSTRAINT [PK_ProductImages] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_ProductImages_Products_ProductId] FOREIGN KEY([ProductId]) REFERENCES [Products] ([Id]) ON DELETE CASCADE
)

/*
3 rows from ProductImages table:
Id	ProductId	ImageUrl	IsPrimary
1	25	/uploads/products/3988c163-de66-47d3-8dfb-89e21b992ef6.png	True
*/


CREATE TABLE [ProductReviews] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProductId] INTEGER NOT NULL,
	[Score] INTEGER NOT NULL,
	[Comment] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[UpdatedAt] DATETIME2 NULL,
	CONSTRAINT [PK_ProductReviews] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_ProductReviews_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_ProductReviews_Products_ProductId] FOREIGN KEY([ProductId]) REFERENCES [Products] ([Id]) ON DELETE CASCADE
)

/*
3 rows from ProductReviews table:
Id	UserId	ProductId	Score	Comment	CreatedAt	UpdatedAt

*/


CREATE TABLE [Products] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CategoryId] INTEGER NOT NULL,
	[SubcategoryId] INTEGER NOT NULL,
	[LocationArea] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Condition] INTEGER NOT NULL,
	[ProductType] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Brand] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RentalGuarantee] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] NVARCHAR(200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Description] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FinalPricePerDay] DECIMAL(10, 2) NOT NULL,
	[TermsConditions] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Status] INTEGER NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[AverageRating] FLOAT(53) NOT NULL DEFAULT ((0.0000000000000000e+000)),
	[BasePricePerDay] DECIMAL(10, 2) NOT NULL DEFAULT ((0.0)),
	[TotalReviews] INTEGER NOT NULL DEFAULT ((0)),
	[TotalPlatformProfit] DECIMAL(18, 2) NOT NULL DEFAULT ((0.0)),
	[TotalRentalCount] INTEGER NOT NULL DEFAULT ((0)),
	CONSTRAINT [PK_Products] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Products_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_Products_Categories_CategoryId] FOREIGN KEY([CategoryId]) REFERENCES [Categories] ([Id]),
	CONSTRAINT [FK_Products_Subcategories_SubcategoryId] FOREIGN KEY([SubcategoryId]) REFERENCES [Subcategories] ([Id])
)

/*
3 rows from Products table:
Id	UserId	CategoryId	SubcategoryId	LocationArea	Condition	ProductType	Brand	RentalGuarantee	Name	Description	FinalPricePerDay	TermsConditions	Status	CreatedAt	AverageRating	BasePricePerDay	TotalReviews	TotalPlatformProfit	TotalRentalCount
5	8b0c078d-f802-4b7d-a8db-88cf2410a6cf	1	101	Nasr City	1	Electronics	Sony	1	PlayStation 5	PS5 with 2 controllers	200.00	Return in same condition	2	2026-04-07 14:47:41.552038	0.0	0.00	0	0.00	0
6	8b0c078d-f802-4b7d-a8db-88cf2410a6cf	1	102	Heliopolis	2	Electronics	Microsoft	1	Xbox Series X	Xbox with wireless controller	180.00	No damage allowed	1	2026-04-07 14:47:41.552038	0.0	0.00	0	0.00	0
7	8b0c078d-f802-4b7d-a8db-88cf2410a6cf	2	201	Maadi	1	Sports	Trinx	0	Mountain Bike	Professional mountain bike	90.00	Helmet included	1	2026-04-07 14:47:41.552038	0.0	0.00	0	0.00	0
*/


CREATE TABLE [RentalOrderDetails] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[RentalOrderId] INTEGER NOT NULL,
	[StartDate] DATETIME2 NOT NULL,
	[EndDate] DATETIME2 NOT NULL,
	[DeliveryMethod] INTEGER NOT NULL,
	[DeliveryAddress] NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AddressId] INTEGER NULL,
	CONSTRAINT [PK_RentalOrderDetails] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_RentalOrderDetails_RentalOrders_RentalOrderId] FOREIGN KEY([RentalOrderId]) REFERENCES [RentalOrders] ([Id]) ON DELETE CASCADE
)

/*
3 rows from RentalOrderDetails table:
Id	RentalOrderId	StartDate	EndDate	DeliveryMethod	DeliveryAddress	AddressId

*/


CREATE TABLE [RentalOrders] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[ProductId] INTEGER NOT NULL,
	[RenterId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OwnerId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Status] INTEGER NOT NULL,
	[TotalPrice] DECIMAL(10, 2) NOT NULL,
	[DeliveryFee] DECIMAL(10, 2) NOT NULL,
	[TotalAmount] DECIMAL(10, 2) NOT NULL,
	[TermsAgreed] BIT NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[UpdatedAt] DATETIME2 NULL,
	CONSTRAINT [PK_RentalOrders] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_RentalOrders_AspNetUsers_OwnerId] FOREIGN KEY([OwnerId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_RentalOrders_AspNetUsers_RenterId] FOREIGN KEY([RenterId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_RentalOrders_Products_ProductId] FOREIGN KEY([ProductId]) REFERENCES [Products] ([Id]) ON DELETE CASCADE
)

/*
3 rows from RentalOrders table:
Id	ProductId	RenterId	OwnerId	Status	TotalPrice	DeliveryFee	TotalAmount	TermsAgreed	CreatedAt	UpdatedAt

*/


CREATE TABLE [Reviews] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[ReviewerId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RevieweeId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RentalOrderId] INTEGER NOT NULL,
	[Score] INTEGER NOT NULL,
	[Comment] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] INTEGER NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[UpdatedAt] DATETIME2 NULL,
	CONSTRAINT [PK_Reviews] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Reviews_AspNetUsers_RevieweeId] FOREIGN KEY([RevieweeId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_Reviews_AspNetUsers_ReviewerId] FOREIGN KEY([ReviewerId]) REFERENCES [AspNetUsers] ([Id]),
	CONSTRAINT [FK_Reviews_RentalOrders_RentalOrderId] FOREIGN KEY([RentalOrderId]) REFERENCES [RentalOrders] ([Id])
)

/*
3 rows from Reviews table:
Id	ReviewerId	RevieweeId	RentalOrderId	Score	Comment	Status	CreatedAt	UpdatedAt

*/


CREATE TABLE [Subcategories] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[CategoryId] INTEGER NOT NULL,
	[Name] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT [PK_Subcategories] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Subcategories_Categories_CategoryId] FOREIGN KEY([CategoryId]) REFERENCES [Categories] ([Id]) ON DELETE CASCADE
)

/*
3 rows from Subcategories table:
Id	CategoryId	Name
101	1	PlayStation
102	1	Xbox
201	2	Bikes
*/


CREATE TABLE [Subscriptions] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Price] DECIMAL(10, 2) NOT NULL,
	[DurationDays] INTEGER NOT NULL,
	[Features] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_Subscriptions] PRIMARY KEY ([Id])
)

/*
3 rows from Subscriptions table:
Id	Name	Price	DurationDays	Features	CreatedAt
1	one month	0.00	30	string	2026-04-13 00:47:34.116170
*/


CREATE TABLE [UserAddresses] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AddressLine] NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[City] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Area] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDefault] BIT NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_UserAddresses] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_UserAddresses_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
)

/*
3 rows from UserAddresses table:
Id	UserId	AddressLine	City	Area	IsDefault	CreatedAt

*/


CREATE TABLE [UserSubscriptions] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SubscriptionId] INTEGER NOT NULL,
	[StartDate] DATETIME2 NOT NULL,
	[EndDate] DATETIME2 NOT NULL,
	[Status] INTEGER NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_UserSubscriptions] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_UserSubscriptions_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_UserSubscriptions_Subscriptions_SubscriptionId] FOREIGN KEY([SubscriptionId]) REFERENCES [Subscriptions] ([Id])
)

/*
3 rows from UserSubscriptions table:
Id	UserId	SubscriptionId	StartDate	EndDate	Status	CreatedAt
1	83e358a2-997c-4478-a698-380fb6f02353	1	2026-04-13 00:51:51.739758	2026-05-13 00:51:51.739839	0	2026-04-13 00:51:51.740047
*/


CREATE TABLE [WalletTransactions] (
	[Id] INTEGER NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR(450) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Amount] DECIMAL(10, 2) NOT NULL,
	[Type] INTEGER NOT NULL,
	[ReferenceId] INTEGER NULL,
	[Description] NVARCHAR(max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	CONSTRAINT [PK_WalletTransactions] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_WalletTransactions_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
)

/*
3 rows from WalletTransactions table:
Id	UserId	Amount	Type	ReferenceId	Description	CreatedAt
1	83e358a2-997c-4478-a698-380fb6f02353	0.00	1	None	الاشتراك في باقة one month	2026-04-13 00:51:51.691471
*/


CREATE TABLE [__EFMigrationsHistory] (
	[MigrationId] NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProductVersion] NVARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
)

/*
3 rows from __EFMigrationsHistory table:
MigrationId	ProductVersion
20260404233906_init	8.0.25
20260412145327_updateUser	8.0.25
20260412151300_block	8.0.25
*/

In [8]:
import sqlalchemy as sa

try:
    # إنشاء Inspector لقاعدة البيانات
    inspector = sa.inspect(engine)
    
    # جلب جميع أسماء الجداول
    tables = inspector.get_table_names()
    
    print("=" * 50)
    print(f"Total Tables Found: {len(tables)}")
    print("=" * 50)
    
    for table in tables:
        print(f"- {table}")
        
except Exception as e:
    print(f"Failed to fetch tables: {e}")

==================================================
Total Tables Found: 23
==================================================
- __EFMigrationsHistory
- AspNetRoleClaims
- AspNetRoles
- AspNetUserClaims
- AspNetUserLogins
- AspNetUserRoles
- AspNetUsers
- AspNetUserTokens
- Categories
- ChatMessages
- Favorites
- PlatformSettings
- ProductImages
- ProductReviews
- Products
- RentalOrderDetails
- RentalOrders
- Reviews
- Subcategories
- Subscriptions
- UserAddresses
- UserSubscriptions
- WalletTransactions

In [9]:
import pandas as pd

try:
    # كتابة الاستعلام لجلب كل البيانات من جدول Products
    query = "SELECT * FROM Products"
    
    # قراءة البيانات وعرضها في DataFrame
    df_products = pd.read_sql_query(query, engine)
    
    # عرض البيانات (ستظهر كجدول منسق)
    display(df_products)
    
    # إذا كان الجدول كبيراً جداً وتريد عرض أول 10 صفوف فقط، يمكنك استخدام:
    # display(df_products.head(10))
    
except Exception as e:
    print(f"Failed to fetch data: {e}")

,Id,UserId,CategoryId,SubcategoryId,LocationArea,Condition,ProductType,Brand,RentalGuarantee,Name,Description,FinalPricePerDay,TermsConditions,Status,CreatedAt,AverageRating,BasePricePerDay,TotalReviews,TotalPlatformProfit,TotalRentalCount
0,5,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,1,101,Nasr City,1,Electronics,Sony,1,PlayStation 5,PS5 with 2 controllers,200.0,Return in same condition,2,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
1,6,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,1,102,Heliopolis,2,Electronics,Microsoft,1,Xbox Series X,Xbox with wireless controller,180.0,No damage allowed,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
2,7,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,2,201,Maadi,1,Sports,Trinx,0,Mountain Bike,Professional mountain bike,90.0,Helmet included,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
3,8,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,2,202,Dokki,2,Sports,Galaxy,0,City Bike,Comfortable city bicycle,70.0,Return clean,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
4,9,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,3,301,Nasr City,1,Electronics,Canon,1,Canon DSLR Camera,Canon DSLR with lens,150.0,No scratches,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
5,10,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,3,302,Helwan,2,Electronics,Nikon,1,Nikon Camera,Nikon camera with tripod,140.0,Handle carefully,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
6,11,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,4,401,Zamalek,1,Computers,Dell,1,Dell Laptop,Core i7 laptop 16GB RAM,220.0,No software install,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
7,12,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,4,402,Nasr City,2,Computers,HP,0,HP Laptop,Core i5 laptop,150.0,Return charged,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
8,13,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,5,501,Maadi,1,Projectors,Epson,1,Epson Projector,Full HD projector,130.0,Indoor use only,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
9,14,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,5,502,Dokki,2,Projectors,BenQ,1,BenQ Projector,Portable projector,120.0,No dropping,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
10,15,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,6,601,Heliopolis,1,Tools,Bosch,0,Electric Drill,Bosch heavy-duty drill,60.0,Return with case,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
11,16,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,6,602,Nasr City,2,Tools,Makita,0,Angle Grinder,Makita grinder,55.0,Safety required,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
12,17,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,7,701,Maadi,1,Gaming,Logitech,0,Gaming Steering Wheel,Wheel for racing games,80.0,Return intact,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
13,18,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,7,702,Dokki,2,Gaming,Razer,0,Gaming Keyboard,RGB mechanical keyboard,40.0,No liquid damage,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
14,19,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,8,801,Zamalek,1,Audio,JBL,0,JBL Speaker,Portable Bluetooth speaker,50.0,Return charged,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
15,20,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,8,802,Nasr City,2,Audio,Sony,0,Sony Headphones,Noise cancelling headphones,45.0,No scratches,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
16,21,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,9,901,Heliopolis,1,Photography,GoPro,1,GoPro Hero 11,Action camera waterproof,160.0,Return accessories,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
17,22,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,9,902,Maadi,2,Photography,DJI,1,DJI Gimbal,Camera stabilizer,100.0,Handle carefully,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
18,23,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,10,1001,Nasr City,1,Furniture,IKEA,0,Office Chair,Comfortable office chair,30.0,Indoor use only,3,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
19,25,83e358a2-997c-4478-a698-380fb6f02353,1,101,k,0,k,nike,1000,shose,wow,100.0,do not break it,1,2026-04-13 00:53:46.900573,0.0,0.0,0,0.0,0
20,26,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:46:12.009093,0.0,0.0,0,0.0,0
21,27,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,3,2026-04-14 23:47:17.518700,0.0,0.0,0,0.0,0
22,28,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:47:20.405377,0.0,0.0,0,0.0,0
23,29,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,2,2026-04-14 23:47:22.558370,0.0,0.0,0,0.0,0
24,30,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,2,2026-04-14 23:47:23.337642,0.0,0.0,0,0.0,0
25,31,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,1,2026-04-14 23:47:23.982656,0.0,0.0,0,0.0,0
26,33,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:47:25.139928,0.0,0.0,0,0.0,0
27,34,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:47:25.634191,0.0,0.0,0,0.0,0

In [10]:
from sqlalchemy import text

try:
    # فتح اتصال بقاعدة البيانات
    with engine.connect() as conn:
        # جلب أول 10 منتجات (ويمكنك إزالة TOP 10 لجلب الكل)
        result = conn.execute(text("SELECT TOP 10 * FROM Products"))
        
        # طباعة أسماء الأعمدة (Columns)
        print("Columns:", list(result.keys()))
        print("-" * 80)
        
        # طباعة الصفوف
        for row in result:
            print(row)
            
except Exception as e:
    print(f"Failed to fetch data: {e}")

Columns: ['Id', 'UserId', 'CategoryId', 'SubcategoryId', 'LocationArea', 'Condition', 'ProductType', 'Brand', 'RentalGuarantee', 'Name', 'Description', 'FinalPricePerDay', 'TermsConditions', 'Status', 'CreatedAt', 'AverageRating', 'BasePricePerDay', 'TotalReviews', 'TotalPlatformProfit', 'TotalRentalCount']
--------------------------------------------------------------------------------
(5, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 1, 101, 'Nasr City', 1, 'Electronics', 'Sony', '1', 'PlayStation 5', 'PS5 with 2 controllers', Decimal('200.00'), 'Return in same condition', 2, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(6, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 1, 102, 'Heliopolis', 2, 'Electronics', 'Microsoft', '1', 'Xbox Series X', 'Xbox with wireless controller', Decimal('180.00'), 'No damage allowed', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(7, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 2, 201, 'Maadi', 1, 'Sports', 'Trinx', '0', 'Mountain Bike', 'Professional mountain bike', Decimal('90.00'), 'Helmet included', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(8, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 2, 202, 'Dokki', 2, 'Sports', 'Galaxy', '0', 'City Bike', 'Comfortable city bicycle', Decimal('70.00'), 'Return clean', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(9, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 3, 301, 'Nasr City', 1, 'Electronics', 'Canon', '1', 'Canon DSLR Camera', 'Canon DSLR with lens', Decimal('150.00'), 'No scratches', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(10, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 3, 302, 'Helwan', 2, 'Electronics', 'Nikon', '1', 'Nikon Camera', 'Nikon camera with tripod', Decimal('140.00'), 'Handle carefully', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(11, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 4, 401, 'Zamalek', 1, 'Computers', 'Dell', '1', 'Dell Laptop', 'Core i7 laptop 16GB RAM', Decimal('220.00'), 'No software install', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(12, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 4, 402, 'Nasr City', 2, 'Computers', 'HP', '0', 'HP Laptop', 'Core i5 laptop', Decimal('150.00'), 'Return charged', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(13, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 5, 501, 'Maadi', 1, 'Projectors', 'Epson', '1', 'Epson Projector', 'Full HD projector', Decimal('130.00'), 'Indoor use only', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)
(14, '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 5, 502, 'Dokki', 2, 'Projectors', 'BenQ', '1', 'BenQ Projector', 'Portable projector', Decimal('120.00'), 'No dropping', 1, datetime.datetime(2026, 4, 7, 14, 47, 41, 552038), 0.0, Decimal('0.00'), 0, Decimal('0.00'), 0)

In [11]:
import pandas as pd
import random
from datetime import datetime

try:
    # 1. جلب قائمة بـ IDs المستخدمين الحقيقيين من قاعدة البيانات
    users_df = pd.read_sql_query("SELECT Id FROM AspNetUsers", engine)
    valid_user_ids = users_df['Id'].tolist()
    
    if not valid_user_ids:
        print("⚠️ جدول المستخدمين AspNetUsers فارغ! لا يمكنك إضافة منتجات قبل تسجيل حساب مستخدم واحد على الأقل في النظام.")
        
    else:
        print(f"تم العثور على {len(valid_user_ids)} مستخدمين حقيقيين في النظام. سيتم التوزيع عليهم عشوائياً...")
        
        # 2. تجهيز البيانات لكن المرة دي هنسحب UserId عشوائي من اللي موجودين في القاعدة
        # وكمان حولنا النصوص (New/Available) لأرقام مباشرة (1 و 2)
        raw_data = [
            [random.choice(valid_user_ids),1,101,"Nasr City",1,"Electronics","Sony",1,"PlayStation 5", "PS5 with 2 controllers",200,"Return in same condition",1,datetime.now()],
            [random.choice(valid_user_ids),1,102,"Heliopolis",2,"Electronics","Microsoft",1,"Xbox Series X", "Xbox with wireless controller",180,"No damage allowed",1,datetime.now()],
            [random.choice(valid_user_ids),2,201,"Maadi",1,"Sports","Trinx",0,"Mountain Bike", "Professional mountain bike",90,"Helmet included",1,datetime.now()],
            [random.choice(valid_user_ids),2,202,"Dokki",2,"Sports","Galaxy",0,"City Bike", "Comfortable city bicycle",70,"Return clean",1,datetime.now()],
            [random.choice(valid_user_ids),3,301,"Nasr City",1,"Electronics","Canon",1,"Canon DSLR Camera", "Canon DSLR with lens",150,"No scratches",1,datetime.now()],
            [random.choice(valid_user_ids),3,302,"Helwan",2,"Electronics","Nikon",1,"Nikon Camera", "Nikon camera with tripod",140,"Handle carefully",1,datetime.now()],
            [random.choice(valid_user_ids),4,401,"Zamalek",1,"Computers","Dell",1,"Dell Laptop", "Core i7 laptop 16GB RAM",220,"No software install",1,datetime.now()],
            [random.choice(valid_user_ids),4,402,"Nasr City",2,"Computers","HP",0,"HP Laptop", "Core i5 laptop",150,"Return charged",1,datetime.now()],
            [random.choice(valid_user_ids),5,501,"Maadi",1,"Projectors","Epson",1,"Epson Projector", "Full HD projector",130,"Indoor use only",1,datetime.now()],
            [random.choice(valid_user_ids),5,502,"Dokki",2,"Projectors","BenQ",1,"BenQ Projector", "Portable projector",120,"No dropping",1,datetime.now()],
            [random.choice(valid_user_ids),6,601,"Heliopolis",1,"Tools","Bosch",0,"Electric Drill", "Bosch heavy-duty drill",60,"Return with case",1,datetime.now()],
            [random.choice(valid_user_ids),6,602,"Nasr City",2,"Tools","Makita",0,"Angle Grinder", "Makita grinder",55,"Safety required",1,datetime.now()],
            [random.choice(valid_user_ids),7,701,"Maadi",1,"Gaming","Logitech",0,"Gaming Steering Wheel", "Wheel for racing games",80,"Return intact",1,datetime.now()],
            [random.choice(valid_user_ids),7,702,"Dokki",2,"Gaming","Razer",0,"Gaming Keyboard", "RGB mechanical keyboard",40,"No liquid damage",1,datetime.now()],
            [random.choice(valid_user_ids),8,801,"Zamalek",1,"Audio","JBL",0,"JBL Speaker", "Portable Bluetooth speaker",50,"Return charged",1,datetime.now()],
            [random.choice(valid_user_ids),8,802,"Nasr City",2,"Audio","Sony",0,"Sony Headphones", "Noise cancelling headphones",45,"No scratches",1,datetime.now()],
            [random.choice(valid_user_ids),9,901,"Heliopolis",1,"Photography","GoPro",1,"GoPro Hero 11", "Action camera waterproof",160,"Return accessories",1,datetime.now()],
            [random.choice(valid_user_ids),9,902,"Maadi",2,"Photography","DJI",1,"DJI Gimbal", "Camera stabilizer",100,"Handle carefully",1,datetime.now()],
            [random.choice(valid_user_ids),10,1001,"Nasr City",1,"Furniture","IKEA",0,"Office Chair", "Comfortable office chair",30,"Indoor use only",1,datetime.now()],
            [random.choice(valid_user_ids),10,1002,"Dokki",2,"Furniture","Generic",0,"Folding Table", "Portable folding table",25,"Return clean",1,datetime.now()]
        ]

        products_data = pd.DataFrame(raw_data, columns=[
            "UserId","CategoryId","SubcategoryId","LocationArea","Condition",
            "ProductType","Brand","RentalGuarantee","Name","Description",
            "PricePerDay","TermsConditions","Status","CreatedAt"
        ])

        # 3. حفظ البيانات في الـ Database
        products_data.to_sql('Products', con=engine, if_exists='append', index=False)
        print("تم إضافة الـ 20 منتج بنجاح ✅")

except Exception as e:
    print(f"حدث خطأ أثناء الإضافة: {e}")

تم العثور على 14 مستخدمين حقيقيين في النظام. سيتم التوزيع عليهم عشوائياً...
حدث خطأ أثناء الإضافة: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: INSERT INTO [Products] ([UserId], [CategoryId], [SubcategoryId], [LocationArea], [Condition], [ProductType], [Brand], [RentalGuarantee], [Name], [Description], [PricePerDay], [TermsConditions], [Status], [CreatedAt]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ? ... 752 characters truncated ...  ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('eb43366e-0762-4f8a-9a43-ea0e0d542705', 1, 101, 'Nasr City', 1, 'Electronics', 'Sony', 1, 'PlayStation 5', 'PS5 with 2 controllers', 200, 'Return in same condition', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865), '83e358a2-997c-4478-a698-380fb6f02353', 1, 102, 'Heliopolis', 2, 'Electronics', 'Microsoft', 1, 'Xbox Series X', 'Xbox with wireless controller', 180, 'No damage allowed', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865), 'e50e52aa-d944-440b-92c8-26c19af2e3dc', 2, 201, 'Maadi', 1, 'Sports', 'Trinx', 0, 'Mountain Bike', 'Professional mountain bike', 90, 'Helmet included', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865), '2f232163-3a47-445a-98a6-1190154ff732', 2, 202, 'Dokki', 2, 'Sports', 'Galaxy', 0 ... 180 parameters truncated ... 'GoPro', 1, 'GoPro Hero 11', 'Action camera waterproof', 160, 'Return accessories', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865), 'eb43366e-0762-4f8a-9a43-ea0e0d542705', 9, 902, 'Maadi', 2, 'Photography', 'DJI', 1, 'DJI Gimbal', 'Camera stabilizer', 100, 'Handle carefully', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865), '8b0c078d-f802-4b7d-a8db-88cf2410a6cf', 10, 1001, 'Nasr City', 1, 'Furniture', 'IKEA', 0, 'Office Chair', 'Comfortable office chair', 30, 'Indoor use only', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865), 'e5dd40c7-47a7-4524-85cf-3aa217b8da22', 10, 1002, 'Dokki', 2, 'Furniture', 'Generic', 0, 'Folding Table', 'Portable folding table', 25, 'Return clean', 1, datetime.datetime(2026, 4, 15, 13, 37, 34, 765865))]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [12]:
import pandas as pd

try:
    # كتابة الاستعلام لجلب كل البيانات من جدول Products
    query = "SELECT * FROM Products"
    
    # قراءة البيانات وعرضها في DataFrame
    df_products = pd.read_sql_query(query, engine)
    
    # عرض البيانات (ستظهر كجدول منسق)
    display(df_products)
    
    # إذا كان الجدول كبيراً جداً وتريد عرض أول 10 صفوف فقط، يمكنك استخدام:
    # display(df_products.head(10))
    
except Exception as e:
    print(f"Failed to fetch data: {e}")

,Id,UserId,CategoryId,SubcategoryId,LocationArea,Condition,ProductType,Brand,RentalGuarantee,Name,Description,FinalPricePerDay,TermsConditions,Status,CreatedAt,AverageRating,BasePricePerDay,TotalReviews,TotalPlatformProfit,TotalRentalCount
0,5,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,1,101,Nasr City,1,Electronics,Sony,1,PlayStation 5,PS5 with 2 controllers,200.0,Return in same condition,2,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
1,6,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,1,102,Heliopolis,2,Electronics,Microsoft,1,Xbox Series X,Xbox with wireless controller,180.0,No damage allowed,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
2,7,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,2,201,Maadi,1,Sports,Trinx,0,Mountain Bike,Professional mountain bike,90.0,Helmet included,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
3,8,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,2,202,Dokki,2,Sports,Galaxy,0,City Bike,Comfortable city bicycle,70.0,Return clean,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
4,9,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,3,301,Nasr City,1,Electronics,Canon,1,Canon DSLR Camera,Canon DSLR with lens,150.0,No scratches,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
5,10,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,3,302,Helwan,2,Electronics,Nikon,1,Nikon Camera,Nikon camera with tripod,140.0,Handle carefully,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
6,11,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,4,401,Zamalek,1,Computers,Dell,1,Dell Laptop,Core i7 laptop 16GB RAM,220.0,No software install,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
7,12,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,4,402,Nasr City,2,Computers,HP,0,HP Laptop,Core i5 laptop,150.0,Return charged,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
8,13,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,5,501,Maadi,1,Projectors,Epson,1,Epson Projector,Full HD projector,130.0,Indoor use only,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
9,14,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,5,502,Dokki,2,Projectors,BenQ,1,BenQ Projector,Portable projector,120.0,No dropping,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
10,15,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,6,601,Heliopolis,1,Tools,Bosch,0,Electric Drill,Bosch heavy-duty drill,60.0,Return with case,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
11,16,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,6,602,Nasr City,2,Tools,Makita,0,Angle Grinder,Makita grinder,55.0,Safety required,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
12,17,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,7,701,Maadi,1,Gaming,Logitech,0,Gaming Steering Wheel,Wheel for racing games,80.0,Return intact,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
13,18,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,7,702,Dokki,2,Gaming,Razer,0,Gaming Keyboard,RGB mechanical keyboard,40.0,No liquid damage,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
14,19,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,8,801,Zamalek,1,Audio,JBL,0,JBL Speaker,Portable Bluetooth speaker,50.0,Return charged,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
15,20,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,8,802,Nasr City,2,Audio,Sony,0,Sony Headphones,Noise cancelling headphones,45.0,No scratches,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
16,21,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,9,901,Heliopolis,1,Photography,GoPro,1,GoPro Hero 11,Action camera waterproof,160.0,Return accessories,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
17,22,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,9,902,Maadi,2,Photography,DJI,1,DJI Gimbal,Camera stabilizer,100.0,Handle carefully,1,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
18,23,8b0c078d-f802-4b7d-a8db-88cf2410a6cf,10,1001,Nasr City,1,Furniture,IKEA,0,Office Chair,Comfortable office chair,30.0,Indoor use only,3,2026-04-07 14:47:41.552038,0.0,0.0,0,0.0,0
19,25,83e358a2-997c-4478-a698-380fb6f02353,1,101,k,0,k,nike,1000,shose,wow,100.0,do not break it,1,2026-04-13 00:53:46.900573,0.0,0.0,0,0.0,0
20,26,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:46:12.009093,0.0,0.0,0,0.0,0
21,27,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,3,2026-04-14 23:47:17.518700,0.0,0.0,0,0.0,0
22,28,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:47:20.405377,0.0,0.0,0,0.0,0
23,29,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,2,2026-04-14 23:47:22.558370,0.0,0.0,0,0.0,0
24,30,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,2,2026-04-14 23:47:23.337642,0.0,0.0,0,0.0,0
25,31,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,1,2026-04-14 23:47:23.982656,0.0,0.0,0,0.0,0
26,33,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:47:25.139928,0.0,0.0,0,0.0,0
27,34,83e358a2-997c-4478-a698-380fb6f02353,1,101,string,1,string,string,string,string,string,0.0,string,0,2026-04-14 23:47:25.634191,0.0,0.0,0,0.0,0

In [13]:
import pandas as pd
import uuid
import random
from datetime import datetime

# 1. إنشاء حساب مستخدم وهمي (تجريبي)
user_id = str(uuid.uuid4()) # إنشاء ID فريد للمستخدم
national_id = str(random.randint(10000000000000, 99999999999999)) # رقم قومي عشوائي من 14 رقم
username = f"testuser_{random.randint(1000,9999)}"

new_user = pd.DataFrame([{
    "Id": user_id,
    "FullName": "Test User",
    "NationalId": national_id,
    "IdCardImage": "dummy_image.jpg",
    "AccountStatus": 1,
    "Balance": 0.0,
    "CreatedAt": datetime.now(),
    "UserName": username,
    "NormalizedUserName": username.upper(),
    "Email": f"{username}@test.com",
    "NormalizedEmail": f"{username.upper()}@TEST.COM",
    "EmailConfirmed": False,
    "PhoneNumberConfirmed": False,
    "TwoFactorEnabled": False,
    "LockoutEnabled": False,
    "AccessFailedCount": 0
}])

try:
    # 2. حفظ المستخدم في قاعدة البيانات
    new_user.to_sql('AspNetUsers', con=engine, if_exists='append', index=False)
    print(f"تم إنشاء حساب مستخدم بنجاح! الـ ID الخاص به هو: {user_id}")
    
    # 3. إعداد بيانات المنتجات وربطها بحساب المستخدم الجديد
    raw_data = [
        [user_id,1,101,"Nasr City",1,"Electronics","Sony",1,"PlayStation 5", "PS5 with 2 controllers",200,"Return in same condition",1,datetime.now()],
        [user_id,1,102,"Heliopolis",2,"Electronics","Microsoft",1,"Xbox Series X", "Xbox with wireless controller",180,"No damage allowed",1,datetime.now()],
        [user_id,2,201,"Maadi",1,"Sports","Trinx",0,"Mountain Bike", "Professional mountain bike",90,"Helmet included",1,datetime.now()],
        [user_id,2,202,"Dokki",2,"Sports","Galaxy",0,"City Bike", "Comfortable city bicycle",70,"Return clean",1,datetime.now()],
        [user_id,3,301,"Nasr City",1,"Electronics","Canon",1,"Canon DSLR Camera", "Canon DSLR with lens",150,"No scratches",1,datetime.now()],
        [user_id,3,302,"Helwan",2,"Electronics","Nikon",1,"Nikon Camera", "Nikon camera with tripod",140,"Handle carefully",1,datetime.now()],
        [user_id,4,401,"Zamalek",1,"Computers","Dell",1,"Dell Laptop", "Core i7 laptop 16GB RAM",220,"No software install",1,datetime.now()],
        [user_id,4,402,"Nasr City",2,"Computers","HP",0,"HP Laptop", "Core i5 laptop",150,"Return charged",1,datetime.now()],
        [user_id,5,501,"Maadi",1,"Projectors","Epson",1,"Epson Projector", "Full HD projector",130,"Indoor use only",1,datetime.now()],
        [user_id,5,502,"Dokki",2,"Projectors","BenQ",1,"BenQ Projector", "Portable projector",120,"No dropping",1,datetime.now()],
        [user_id,6,601,"Heliopolis",1,"Tools","Bosch",0,"Electric Drill", "Bosch heavy-duty drill",60,"Return with case",1,datetime.now()],
        [user_id,6,602,"Nasr City",2,"Tools","Makita",0,"Angle Grinder", "Makita grinder",55,"Safety required",1,datetime.now()],
        [user_id,7,701,"Maadi",1,"Gaming","Logitech",0,"Gaming Steering Wheel", "Wheel for racing games",80,"Return intact",1,datetime.now()],
        [user_id,7,702,"Dokki",2,"Gaming","Razer",0,"Gaming Keyboard", "RGB mechanical keyboard",40,"No liquid damage",1,datetime.now()],
        [user_id,8,801,"Zamalek",1,"Audio","JBL",0,"JBL Speaker", "Portable Bluetooth speaker",50,"Return charged",1,datetime.now()],
        [user_id,8,802,"Nasr City",2,"Audio","Sony",0,"Sony Headphones", "Noise cancelling headphones",45,"No scratches",1,datetime.now()],
        [user_id,9,901,"Heliopolis",1,"Photography","GoPro",1,"GoPro Hero 11", "Action camera waterproof",160,"Return accessories",1,datetime.now()],
        [user_id,9,902,"Maadi",2,"Photography","DJI",1,"DJI Gimbal", "Camera stabilizer",100,"Handle carefully",1,datetime.now()],
        [user_id,10,1001,"Nasr City",1,"Furniture","IKEA",0,"Office Chair", "Comfortable office chair",30,"Indoor use only",1,datetime.now()],
        [user_id,10,1002,"Dokki",2,"Furniture","Generic",0,"Folding Table", "Portable folding table",25,"Return clean",1,datetime.now()]
    ]

    products_data = pd.DataFrame(raw_data, columns=[
        "UserId","CategoryId","SubcategoryId","LocationArea","Condition",
        "ProductType","Brand","RentalGuarantee","Name","Description",
        "PricePerDay","TermsConditions","Status","CreatedAt"
    ])

    # 4. حفظ بيانات المنتجات
    products_data.to_sql('Products', con=engine, if_exists='append', index=False)
    print("تم إضافة الـ 20 منتج بنجاح لرسلهم للمستخدم الجديد ✅")

except Exception as e:
    print(f"حدث خطأ أثناء التنفيذ: {e}")

تم إنشاء حساب مستخدم بنجاح! الـ ID الخاص به هو: 3d9aed33-6f6c-4b29-8d23-283a77257c7e
حدث خطأ أثناء التنفيذ: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: INSERT INTO [Products] ([UserId], [CategoryId], [SubcategoryId], [LocationArea], [Condition], [ProductType], [Brand], [RentalGuarantee], [Name], [Description], [PricePerDay], [TermsConditions], [Status], [CreatedAt]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ? ... 752 characters truncated ...  ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('3d9aed33-6f6c-4b29-8d23-283a77257c7e', 1, 101, 'Nasr City', 1, 'Electronics', 'Sony', 1, 'PlayStation 5', 'PS5 with 2 controllers', 200, 'Return in same condition', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301), '3d9aed33-6f6c-4b29-8d23-283a77257c7e', 1, 102, 'Heliopolis', 2, 'Electronics', 'Microsoft', 1, 'Xbox Series X', 'Xbox with wireless controller', 180, 'No damage allowed', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301), '3d9aed33-6f6c-4b29-8d23-283a77257c7e', 2, 201, 'Maadi', 1, 'Sports', 'Trinx', 0, 'Mountain Bike', 'Professional mountain bike', 90, 'Helmet included', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301), '3d9aed33-6f6c-4b29-8d23-283a77257c7e', 2, 202, 'Dokki', 2, 'Sports', 'Galaxy', 0 ... 180 parameters truncated ... 'GoPro', 1, 'GoPro Hero 11', 'Action camera waterproof', 160, 'Return accessories', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301), '3d9aed33-6f6c-4b29-8d23-283a77257c7e', 9, 902, 'Maadi', 2, 'Photography', 'DJI', 1, 'DJI Gimbal', 'Camera stabilizer', 100, 'Handle carefully', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301), '3d9aed33-6f6c-4b29-8d23-283a77257c7e', 10, 1001, 'Nasr City', 1, 'Furniture', 'IKEA', 0, 'Office Chair', 'Comfortable office chair', 30, 'Indoor use only', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301), '3d9aed33-6f6c-4b29-8d23-283a77257c7e', 10, 1002, 'Dokki', 2, 'Furniture', 'Generic', 0, 'Folding Table', 'Portable folding table', 25, 'Return clean', 1, datetime.datetime(2026, 4, 15, 13, 37, 54, 337301))]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [14]:
import pandas as pd
import uuid
import random
from datetime import datetime
from sqlalchemy import text

try:
    with engine.begin() as conn:
        # 1. إدراج أو تجهيز الأقسام الرئيسية (Categories)
        categories = [(1, 'Electronics'), (2, 'Sports'), (3, 'Cameras'), (4, 'Computers'), 
                      (5, 'Projectors'), (6, 'Tools'), (7, 'Gaming'), (8, 'Audio'), 
                      (9, 'Photography'), (10, 'Furniture')]
        
        print("جاري إنشاء الأقسام (Categories)...")
        for cid, cname in categories:
            # نحاول إضافة الأقسام مع تفعيل الـ Identity Insert أو بدونها
            try:
                conn.execute(text(f"SET IDENTITY_INSERT Categories ON; INSERT INTO Categories (Id, Name, CreatedAt) VALUES ({cid}, '{cname}', GETDATE()); SET IDENTITY_INSERT Categories OFF;"))
            except:
                try:
                    conn.execute(text(f"INSERT INTO Categories (Id, Name, CreatedAt) VALUES ({cid}, '{cname}', GETDATE())"))
                except:
                    pass # إذا كان القسم موجود مسبقاً، نتجاهل الإضافة

        # 2. إدراج الأقسام الفرعية (SubCategories)
        subcategories = [(101, 1, 'PlayStation'), (102, 1, 'Xbox'), (201, 2, 'Bikes'), (202, 2, 'City Bikes'),
                         (301, 3, 'DSLR'), (302, 3, 'Other'), (401, 4, 'Laptops'), (402, 4, 'PCs'),
                         (501, 5, 'HD Projectors'), (502, 5, 'Portable Projectors'), (601, 6, 'Drills'), (602, 6, 'Grinders'),
                         (701, 7, 'Steering Wheels'), (702, 7, 'Keyboards'), (801, 8, 'Speakers'), (802, 8, 'Headphones'),
                         (901, 9, 'Action Cam'), (902, 9, 'Gimbals'), (1001, 10, 'Chairs'), (1002, 10, 'Tables')]
                         
        print("جاري إنشاء الأقسام الفرعية (SubCategories)...")
        for sid, cid, sname in subcategories:
            try:
                conn.execute(text(f"SET IDENTITY_INSERT SubCategories ON; INSERT INTO SubCategories (Id, CategoryId, Name) VALUES ({sid}, {cid}, '{sname}'); SET IDENTITY_INSERT SubCategories OFF;"))
            except:
                try:
                    conn.execute(text(f"INSERT INTO SubCategories (Id, CategoryId, Name) VALUES ({sid}, {cid}, '{sname}')"))
                except:
                    pass # نتجاهله إذا كان موجوداً

# إعداد المستخدم الوهمي إذا نجح بناء الأقسام
user_id = str(uuid.uuid4()) 
national_id = str(random.randint(10000000000000, 99999999999999))
username = f"testuser_{random.randint(1000,9999)}"

new_user = pd.DataFrame([{
    "Id": user_id, "FullName": "Test User", "NationalId": national_id, "IdCardImage": "dummy_image.jpg",
    "AccountStatus": 1, "Balance": 0.0, "CreatedAt": datetime.now(), "UserName": username,
    "NormalizedUserName": username.upper(), "Email": f"{username}@test.com", "NormalizedEmail": f"{username.upper()}@TEST.COM",
    "EmailConfirmed": False, "PhoneNumberConfirmed": False, "TwoFactorEnabled": False, "LockoutEnabled": False, "AccessFailedCount": 0
}])

try:
    print("جاري إنشاء المستخدم الوهمي...")
    new_user.to_sql('AspNetUsers', con=engine, if_exists='append', index=False)
    
    # ربط المنتجات
    print("جاري رفع المنتجات...")
    raw_data = [
        [user_id,1,101,"Nasr City",1,"Electronics","Sony",1,"PlayStation 5", "PS5 with 2 controllers",200,"Return in same condition",1,datetime.now()],
        [user_id,1,102,"Heliopolis",2,"Electronics","Microsoft",1,"Xbox Series X", "Xbox with wireless controller",180,"No damage allowed",1,datetime.now()],
        [user_id,2,201,"Maadi",1,"Sports","Trinx",0,"Mountain Bike", "Professional mountain bike",90,"Helmet included",1,datetime.now()],
        [user_id,2,202,"Dokki",2,"Sports","Galaxy",0,"City Bike", "Comfortable city bicycle",70,"Return clean",1,datetime.now()],
        [user_id,3,301,"Nasr City",1,"Electronics","Canon",1,"Canon DSLR Camera", "Canon DSLR with lens",150,"No scratches",1,datetime.now()],
        [user_id,3,302,"Helwan",2,"Electronics","Nikon",1,"Nikon Camera", "Nikon camera with tripod",140,"Handle carefully",1,datetime.now()],
        [user_id,4,401,"Zamalek",1,"Computers","Dell",1,"Dell Laptop", "Core i7 laptop 16GB RAM",220,"No software install",1,datetime.now()],
        [user_id,4,402,"Nasr City",2,"Computers","HP",0,"HP Laptop", "Core i5 laptop",150,"Return charged",1,datetime.now()],
        [user_id,5,501,"Maadi",1,"Projectors","Epson",1,"Epson Projector", "Full HD projector",130,"Indoor use only",1,datetime.now()],
        [user_id,5,502,"Dokki",2,"Projectors","BenQ",1,"BenQ Projector", "Portable projector",120,"No dropping",1,datetime.now()],
        [user_id,6,601,"Heliopolis",1,"Tools","Bosch",0,"Electric Drill", "Bosch heavy-duty drill",60,"Return with case",1,datetime.now()],
        [user_id,6,602,"Nasr City",2,"Tools","Makita",0,"Angle Grinder", "Makita grinder",55,"Safety required",1,datetime.now()],
        [user_id,7,701,"Maadi",1,"Gaming","Logitech",0,"Gaming Steering Wheel", "Wheel for racing games",80,"Return intact",1,datetime.now()],
        [user_id,7,702,"Dokki",2,"Gaming","Razer",0,"Gaming Keyboard", "RGB mechanical keyboard",40,"No liquid damage",1,datetime.now()],
        [user_id,8,801,"Zamalek",1,"Audio","JBL",0,"JBL Speaker", "Portable Bluetooth speaker",50,"Return charged",1,datetime.now()],
        [user_id,8,802,"Nasr City",2,"Audio","Sony",0,"Sony Headphones", "Noise cancelling headphones",45,"No scratches",1,datetime.now()],
        [user_id,9,901,"Heliopolis",1,"Photography","GoPro",1,"GoPro Hero 11", "Action camera waterproof",160,"Return accessories",1,datetime.now()],
        [user_id,9,902,"Maadi",2,"Photography","DJI",1,"DJI Gimbal", "Camera stabilizer",100,"Handle carefully",1,datetime.now()],
        [user_id,10,1001,"Nasr City",1,"Furniture","IKEA",0,"Office Chair", "Comfortable office chair",30,"Indoor use only",1,datetime.now()],
        [user_id,10,1002,"Dokki",2,"Furniture","Generic",0,"Folding Table", "Portable folding table",25,"Return clean",1,datetime.now()]
    ]

    products_data = pd.DataFrame(raw_data, columns=[
        "UserId","CategoryId","SubcategoryId","LocationArea","Condition",
        "ProductType","Brand","RentalGuarantee","Name","Description",
        "PricePerDay","TermsConditions","Status","CreatedAt"
    ])

    products_data.to_sql('Products', con=engine, if_exists='append', index=False)
    print("تم إضافة الأقسام، المستخدم، والـ 20 منتج بنجاح ✅ مبروووك!")

except Exception as e:
    print(f"حدث خطأ أخير: {e}")

SyntaxError: expected 'except' or 'finally' block (474165308.py, line 43)

In [16]:
import pandas as pd
import uuid
import random
from datetime import datetime
from sqlalchemy import text

# ==========================================
# 1. إعداد الأقسام والأقسام الفرعية
# ==========================================
try:
    with engine.begin() as conn:
        categories = [(1, 'Electronics'), (2, 'Sports'), (3, 'Cameras'), (4, 'Computers'), 
                      (5, 'Projectors'), (6, 'Tools'), (7, 'Gaming'), (8, 'Audio'), 
                      (9, 'Photography'), (10, 'Furniture')]
        
        print("جاري إنشاء الأقسام (Categories)...")
        for cid, cname in categories:
            try:
                conn.execute(text(f"SET IDENTITY_INSERT Categories ON; INSERT INTO Categories (Id, Name, CreatedAt) VALUES ({cid}, '{cname}', GETDATE()); SET IDENTITY_INSERT Categories OFF;"))
            except:
                try:
                    conn.execute(text(f"INSERT INTO Categories (Id, Name, CreatedAt) VALUES ({cid}, '{cname}', GETDATE())"))
                except: pass

        subcategories = [(101, 1, 'PlayStation'), (102, 1, 'Xbox'), (201, 2, 'Bikes'), (202, 2, 'City Bikes'),
                         (301, 3, 'DSLR'), (302, 3, 'Other'), (401, 4, 'Laptops'), (402, 4, 'PCs'),
                         (501, 5, 'HD Projectors'), (502, 5, 'Portable Projectors'), (601, 6, 'Drills'), (602, 6, 'Grinders'),
                         (701, 7, 'Steering Wheels'), (702, 7, 'Keyboards'), (801, 8, 'Speakers'), (802, 8, 'Headphones'),
                         (901, 9, 'Action Cam'), (902, 9, 'Gimbals'), (1001, 10, 'Chairs'), (1002, 10, 'Tables')]
                         
        print("جاري إنشاء الأقسام الفرعية (SubCategories)...")
        for sid, cid, sname in subcategories:
            try:
                conn.execute(text(f"SET IDENTITY_INSERT SubCategories ON; INSERT INTO SubCategories (Id, CategoryId, Name) VALUES ({sid}, {cid}, '{sname}'); SET IDENTITY_INSERT SubCategories OFF;"))
            except:
                try:
                    conn.execute(text(f"INSERT INTO SubCategories (Id, CategoryId, Name) VALUES ({sid}, {cid}, '{sname}')"))
                except: pass
                
except Exception as e:
    print(f"تنبيه (موقتاً): {e}")

# ==========================================
# 2. إعداد المستخدم ورفع المنتجات
# ==========================================
user_id = str(uuid.uuid4()) 
national_id = str(random.randint(10000000000000, 99999999999999))
username = f"testuser_{random.randint(1000,9999)}"

new_user = pd.DataFrame([{
    "Id": user_id, "FullName": "Test User", "NationalId": national_id, "IdCardImage": "dummy_image.jpg",
    "AccountStatus": 1, "Balance": 0.0, "CreatedAt": datetime.now(), "UserName": username,
    "NormalizedUserName": username.upper(), "Email": f"{username}@test.com", "NormalizedEmail": f"{username.upper()}@TEST.COM",
    "EmailConfirmed": False, "PhoneNumberConfirmed": False, "TwoFactorEnabled": False, "LockoutEnabled": False, "AccessFailedCount": 0
}])

try:
    print("جاري إنشاء المستخدم الوهمي...")
    new_user.to_sql('AspNetUsers', con=engine, if_exists='append', index=False)
    
    print("جاري رفع المنتجات...")
    raw_data = [
        [user_id,1,101,"Nasr City",1,"Electronics","Sony",1,"PlayStation 5", "PS5 with 2 controllers",200,"Return in same condition",1,datetime.now()],
        [user_id,1,102,"Heliopolis",2,"Electronics","Microsoft",1,"Xbox Series X", "Xbox with wireless controller",180,"No damage allowed",1,datetime.now()],
        [user_id,2,201,"Maadi",1,"Sports","Trinx",0,"Mountain Bike", "Professional mountain bike",90,"Helmet included",1,datetime.now()],
        [user_id,2,202,"Dokki",2,"Sports","Galaxy",0,"City Bike", "Comfortable city bicycle",70,"Return clean",1,datetime.now()],
        [user_id,3,301,"Nasr City",1,"Electronics","Canon",1,"Canon DSLR Camera", "Canon DSLR with lens",150,"No scratches",1,datetime.now()],
        [user_id,3,302,"Helwan",2,"Electronics","Nikon",1,"Nikon Camera", "Nikon camera with tripod",140,"Handle carefully",1,datetime.now()],
        [user_id,4,401,"Zamalek",1,"Computers","Dell",1,"Dell Laptop", "Core i7 laptop 16GB RAM",220,"No software install",1,datetime.now()],
        [user_id,4,402,"Nasr City",2,"Computers","HP",0,"HP Laptop", "Core i5 laptop",150,"Return charged",1,datetime.now()],
        [user_id,5,501,"Maadi",1,"Projectors","Epson",1,"Epson Projector", "Full HD projector",130,"Indoor use only",1,datetime.now()],
        [user_id,5,502,"Dokki",2,"Projectors","BenQ",1,"BenQ Projector", "Portable projector",120,"No dropping",1,datetime.now()],
        [user_id,6,601,"Heliopolis",1,"Tools","Bosch",0,"Electric Drill", "Bosch heavy-duty drill",60,"Return with case",1,datetime.now()],
        [user_id,6,602,"Nasr City",2,"Tools","Makita",0,"Angle Grinder", "Makita grinder",55,"Safety required",1,datetime.now()],
        [user_id,7,701,"Maadi",1,"Gaming","Logitech",0,"Gaming Steering Wheel", "Wheel for racing games",80,"Return intact",1,datetime.now()],
        [user_id,7,702,"Dokki",2,"Gaming","Razer",0,"Gaming Keyboard", "RGB mechanical keyboard",40,"No liquid damage",1,datetime.now()],
        [user_id,8,801,"Zamalek",1,"Audio","JBL",0,"JBL Speaker", "Portable Bluetooth speaker",50,"Return charged",1,datetime.now()],
        [user_id,8,802,"Nasr City",2,"Audio","Sony",0,"Sony Headphones", "Noise cancelling headphones",45,"No scratches",1,datetime.now()],
        [user_id,9,901,"Heliopolis",1,"Photography","GoPro",1,"GoPro Hero 11", "Action camera waterproof",160,"Return accessories",1,datetime.now()],
        [user_id,9,902,"Maadi",2,"Photography","DJI",1,"DJI Gimbal", "Camera stabilizer",100,"Handle carefully",1,datetime.now()],
        [user_id,10,1001,"Nasr City",1,"Furniture","IKEA",0,"Office Chair", "Comfortable office chair",30,"Indoor use only",1,datetime.now()],
        [user_id,10,1002,"Dokki",2,"Furniture","Generic",0,"Folding Table", "Portable folding table",25,"Return clean",1,datetime.now()]
    ]

    products_data = pd.DataFrame(raw_data, columns=[
        "UserId","CategoryId","SubcategoryId","LocationArea","Condition",
        "ProductType","Brand","RentalGuarantee","Name","Description",
        "PricePerDay","TermsConditions","Status","CreatedAt"
    ])

    products_data.to_sql('Products', con=engine, if_exists='append', index=False)
    print("✅ تمت إضافة الأقسام، والمستخدم الوهمي، والـ 20 منتج بنجاح!")

except Exception as e:
    print(f"❌ حدث خطأ أخير في إنشاء المستخدم أو الرفع: {e}")

جاري إنشاء الأقسام (Categories)...
جاري إنشاء الأقسام الفرعية (SubCategories)...
جاري إنشاء المستخدم الوهمي...
جاري رفع المنتجات...
❌ حدث خطأ أخير في إنشاء المستخدم أو الرفع: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: INSERT INTO [Products] ([UserId], [CategoryId], [SubcategoryId], [LocationArea], [Condition], [ProductType], [Brand], [RentalGuarantee], [Name], [Description], [PricePerDay], [TermsConditions], [Status], [CreatedAt]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ? ... 752 characters truncated ...  ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 1, 101, 'Nasr City', 1, 'Electronics', 'Sony', 1, 'PlayStation 5', 'PS5 with 2 controllers', 200, 'Return in same condition', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797), '1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 1, 102, 'Heliopolis', 2, 'Electronics', 'Microsoft', 1, 'Xbox Series X', 'Xbox with wireless controller', 180, 'No damage allowed', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797), '1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 2, 201, 'Maadi', 1, 'Sports', 'Trinx', 0, 'Mountain Bike', 'Professional mountain bike', 90, 'Helmet included', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797), '1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 2, 202, 'Dokki', 2, 'Sports', 'Galaxy', 0 ... 180 parameters truncated ... 'GoPro', 1, 'GoPro Hero 11', 'Action camera waterproof', 160, 'Return accessories', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797), '1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 9, 902, 'Maadi', 2, 'Photography', 'DJI', 1, 'DJI Gimbal', 'Camera stabilizer', 100, 'Handle carefully', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797), '1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 10, 1001, 'Nasr City', 1, 'Furniture', 'IKEA', 0, 'Office Chair', 'Comfortable office chair', 30, 'Indoor use only', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797), '1b7ef8d7-8e5e-4174-89ff-f1a63402b499', 10, 1002, 'Dokki', 2, 'Furniture', 'Generic', 0, 'Folding Table', 'Portable folding table', 25, 'Return clean', 1, datetime.datetime(2026, 4, 15, 13, 50, 37, 700797))]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [1]:
import pandas as pd

try:
    # كتابة الاستعلام لجلب كل البيانات من جدول Products
    query = "SELECT * FROM Products"
    
    # قراءة البيانات وعرضها في DataFrame
    df_products = pd.read_sql_query(query, engine)
    
    # عرض البيانات (ستظهر كجدول منسق)
    display(df_products)
    
    # إذا كان الجدول كبيراً جداً وتريد عرض أول 10 صفوف فقط، يمكنك استخدام:
    # display(df_products.head(10))
    
except Exception as e:
    print(f"Failed to fetch data: {e}")

Failed to fetch data: name 'engine' is not defined

In [7]:
import pandas as pd

query = """
SELECT 
    p.Id,
    
    -- بيانات المستخدم
    p.UserId,
    u.FullName AS UserName,  -- أو UserName بدل FullName حسب المطلوب المعروض
    
    -- بيانات القسم
    p.CategoryId,
    c.Name AS CategoryName,
    
    -- بيانات القسم الفرعي
    p.SubcategoryId,
    s.Name AS SubcategoryName,
    
    -- باقي بيانات المنتج
    p.LocationArea, 
    p.Condition, 
    p.ProductType, 
    p.Brand, 
    p.RentalGuarantee, 
    p.Name, 
    p.Description, 
    p.PricePerDay, 
    p.TermsConditions, 
    p.Status, 
    p.CreatedAt
    
FROM Products p
LEFT JOIN AspNetUsers u ON p.UserId = u.Id
LEFT JOIN Categories c ON p.CategoryId = c.Id
LEFT JOIN SubCategories s ON p.SubcategoryId = s.Id
"""

try:
    # جلب البيانات المرتبطة من قاعدة البيانات
    df_products_with_names = pd.read_sql_query(query, engine)
    
    # عرض الجدول الجميل والمقروء
    display(df_products_with_names)
    
except Exception as e:
    print(f"حدث خطأ أثناء جلب البيانات: {e}")

حدث خطأ أثناء جلب البيانات: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207) (SQLExecDirectW)")
[SQL:
SELECT
    p.Id,

    -- بيانات المستخدم
    p.UserId,
    u.FullName AS UserName,  -- أو UserName بدل FullName حسب المطلوب المعروض

    -- بيانات القسم
    p.CategoryId,
    c.Name AS CategoryName,

    -- بيانات القسم الفرعي
    p.SubcategoryId,
    s.Name AS SubcategoryName,

    -- باقي بيانات المنتج
    p.LocationArea,
    p.Condition,
    p.ProductType,
    p.Brand,
    p.RentalGuarantee,
    p.Name,
    p.Description,
    p.PricePerDay,
    p.TermsConditions,
    p.Status,
    p.CreatedAt

FROM Products p
LEFT JOIN AspNetUsers u ON p.UserId = u.Id
LEFT JOIN Categories c ON p.CategoryId = c.Id
LEFT JOIN SubCategories s ON p.SubcategoryId = s.Id
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [6]:
from sqlalchemy import text

# إحنا بنقسم الأكواد لأن الـ SQL بيطلب إن أمر Create View يتنفذ لوحده
drop_old_table = """
-- مسح الجدول الثابت لو كان موجود
IF OBJECT_ID('Products_LLm', 'U') IS NOT NULL 
    DROP TABLE Products_LLm;
"""

drop_old_view = """
-- مسح الـ View لو كان موجود قبل كده
IF OBJECT_ID('Products_LLm', 'V') IS NOT NULL 
    DROP VIEW Products_LLm;
"""

create_view_query = """
-- إنشاء الـ View الحي اللي بيربط البيانات ويحدثها تلقائياً
CREATE VIEW Products_LLm AS
SELECT 
    p.Id,
    p.UserId,
    u.FullName AS UserName,
    p.CategoryId,
    c.Name AS CategoryName,
    p.SubcategoryId,
    s.Name AS SubcategoryName,
    p.LocationArea, 
    p.Condition, 
    p.ProductType, 
    p.Brand, 
    p.RentalGuarantee, 
    p.Name, 
    p.Description, 
    p.PricePerDay, 
    p.TermsConditions, 
    p.Status, 
    p.CreatedAt
FROM Products p
LEFT JOIN AspNetUsers u ON p.UserId = u.Id
LEFT JOIN Categories c ON p.CategoryId = c.Id
LEFT JOIN SubCategories s ON p.SubcategoryId = s.Id;
"""

try:
    with engine.begin() as conn:
        conn.execute(text(drop_old_table))
        conn.execute(text(drop_old_view))
        conn.execute(text(create_view_query))
        
        print("تم مسح الجدول الثابت، وإنشاء المنظور الحي (VIEW) باسم 'Products_LLm' بنجاح! 🚀")
        print("دلوقتي أي منتج هيتطاف في الجداول الأصلية، هيسمّع هنا فوراً وفي نفس اللحظة.")
        
except Exception as e:
    print(f"حدث خطأ أثناء الإنشاء: {e}")

حدث خطأ أثناء الإنشاء: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PricePerDay'. (207) (SQLExecDirectW)")
[SQL:
-- إنشاء الـ View الحي اللي بيربط البيانات ويحدثها تلقائياً
CREATE VIEW Products_LLm AS
SELECT
    p.Id,
    p.UserId,
    u.FullName AS UserName,
    p.CategoryId,
    c.Name AS CategoryName,
    p.SubcategoryId,
    s.Name AS SubcategoryName,
    p.LocationArea,
    p.Condition,
    p.ProductType,
    p.Brand,
    p.RentalGuarantee,
    p.Name,
    p.Description,
    p.PricePerDay,
    p.TermsConditions,
    p.Status,
    p.CreatedAt
FROM Products p
LEFT JOIN AspNetUsers u ON p.UserId = u.Id
LEFT JOIN Categories c ON p.CategoryId = c.Id
LEFT JOIN SubCategories s ON p.SubcategoryId = s.Id;
]
(Background on this error at: https://sqlalche.me/e/20/f405)